//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIForMyHealthBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityID { get; set; }
        public Nullable<int> NoOfSteps { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
