//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIForMyHealthBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingsID { get; set; }
        public string SettingName { get; set; }
        public string SettingValue { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
